app = "ananni-log-shipper"
primary_region = "ams"
swap_size_mb = 512

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[metrics]
  port = 9598
  path = "/metrics"

[env]
  ORG = "personal"
  QUEUE = "personal-org-logs"
